# Generated by Django 3.1.6 on 2021-03-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='region_kladr',
            new_name='region_iso',
        ),
    ]
